name: Build macOS App

on:
  push:
    branches:
      - main
      - master # In case your default branch is master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual triggering

jobs:
  build-macos:
    runs-on: macos-latest # Use the latest macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python 3.x version

      - name: Install FFmpeg
        run: brew install ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the macOS app
        run: python3 setup.py py2app # Full build, not alias mode

      - name: Create ZIP of the .app Bundle
        run: |
          cd dist
          zip -r Bilibili-Downloader-macOS.zip "Bilibili Downloader.app"
          cd ..

      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bilibili-Downloader-macOS
          path: dist/Bilibili-Downloader-macOS.zip # Upload the created ZIP file
          if-no-files-found: error # Error if the app is not found 